### PR TITLE
Japanese patch

### PR DESCRIPTION
**Pull request by jh4xsy**
Hi @oe5hpm 

- Original bcm can't handle Double Byte Character Set correct.
I saw many umlaut! in KANJI message.
So I stopped that conversion, then I can read Japanese message.

- I changed the default encoding of http interface.
In Japan, we use Shift_JIS code.

- Updated messages.ja.

### CODE REVIEW

**Comment by jh4xsy** [comment]
Hi @oe5hpm 

I think NO need to support SBCS/DBCS both.
AFAIK, Two other station are using DBCS version of bcm.
So user can specify DBCS option at compile is  enough.

I must define a macro and pass it the preprocessor.

bcm can handle "The Accept-Language request"  and respond charset is the best. But this is  too much!

**Comment by oe5hpm** [comment]
hi iwamato,
compile switch makes it fixed to japanese language, so no other (maybe tourist) has no chance to operate the bbs. i will look for some solution to make this dynamically switchable.

**Comment by jh4xsy** [comment]
I close this and think another way.

**Comment by oe5hpm** [comment]
hi iwamoto,
ok so ... we stay in contact regarding this i think.

cheers,
Hannes

**Pull request closed without merging**
